apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
      version: v1
  template:
    metadata:
      labels:
        app: chatbot
        version: v1
    spec:
      containers:
      - name: chatbot
        image: farhanmullick/chatbot-application:v1
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
      version: v2
  template:
    metadata:
      labels:
        app: chatbot
        version: v2
    spec:
      containers:
      - name: chatbot
        image: farhanmullick/chatbot-application:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: ClusterIP
  selector:
    app: chatbot
    version: v1  # Initially pointing to blue (v1)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000