apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 0
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: farhanmullick/chatbot-application:PLACEHOLDER
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-rolling-service
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000