name: Build, Push & Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: farhanmullick/chatbot-application
  K8S_MANIFEST: .kubernetes/rolling-update-deployment.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Build & Push
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      # Kubernetes Deploy
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure K8s Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: docker-desktop

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ env.K8S_MANIFEST }}
          kubectl rollout status deployment/chatbot-rolling --timeout=90s