name: Build, Push & Deploy with KinD

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: farhanmullick/chatbot-application
  K8S_MANIFEST: .kubernetes/rolling-update-deployment.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Set up KinD cluster
      - name: Create KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          name: github-actions-cluster  # Explicit cluster name
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
            - role: control-plane
              extraPortMappings:
              - containerPort: 3000
                hostPort: 80  # Map host port 80 to container port 3000

      # 2. Build and push to local KinD registry
      - name: Build Docker image
        run: |
          docker build -t ${DOCKER_IMAGE}:latest .
          kind load docker-image ${DOCKER_IMAGE}:latest --name github-actions-cluster

      # 3. Deploy to KinD
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Verify cluster access
        run: |
          kubectl cluster-info --context kind-github-actions-cluster
          kubectl get nodes

      - name: Deploy to KinD
        run: |
          kubectl apply -f ${K8S_MANIFEST} --context kind-github-actions-cluster
          kubectl rollout status deployment/chatbot-rolling --timeout=90s