name: Build, Push & Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: farhanmullick/chatbot-application
  K8S_MANIFEST: .kubernetes/rolling-update-deployment.yaml
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1.8.0

      # Docker Build & Push
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Update deployment image
        run: |
          sed -i "s|IMAGE_TAG|${{ env.IMAGE_TAG }}|g" .kubernetes/rolling-update-deployment.yaml

      # Kubernetes Deploy
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ env.K8S_MANIFEST }}
          kubectl rollout status deployment/chatbot-rolling --timeout=90s